# 基础配置
title: Kun-1319 的博客
description: 北京联合大学信息安全专业 | CTF 爱好者 | Bugku 刷题记录
author: 李昊锟

# 主题
theme: minima

# 社交链接
github_username: Kun-1319
email: lihaokun8122@163.com

# 导航栏配置
header_pages:
  - bugku.md
  - ctfhub.md

# 隐藏 Minima 默认的页脚描述
show_excerpts: false
